# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getV <- function(Y, q) {
    .Call(`_BayesianLASSOMonitoring_getV`, Y, q)
}

rtwosegnorm <- function(n, a, b, mean, sd) {
    .Call(`_BayesianLASSOMonitoring_rtwosegnorm`, n, a, b, mean, sd)
}

getGMat <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getGMat`, T, q)
}

getPhiMat <- function(Phi, T) {
    .Call(`_BayesianLASSOMonitoring_getPhiMat`, Phi, T)
}

getHMatMT <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatMT`, T, q)
}

getHMatSustained <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatSustained`, T, q)
}

getHMatIsolated <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatIsolated`, T, q)
}

getHMatGradual <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatGradual`, T, q)
}

getXSeasonalityFS <- function(T, s, n) {
    .Call(`_BayesianLASSOMonitoring_getXSeasonalityFS`, T, s, n)
}

GibbsRFLSMcpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMcpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, H)
}

GibbsRFLSMUpdatecpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMUpdatecpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, G, oldpars, H)
}

lhf <- function(Y, Phi, Mu, sigma2) {
    .Call(`_BayesianLASSOMonitoring_lhf`, Y, Phi, Mu, sigma2)
}

boxcoxtr <- function(Y, theta) {
    .Call(`_BayesianLASSOMonitoring_boxcoxtr`, Y, theta)
}

invboxcoxtr <- function(Ybc, theta) {
    .Call(`_BayesianLASSOMonitoring_invboxcoxtr`, Ybc, theta)
}

invyeojohnsontr <- function(Yyj, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_invyeojohnsontr`, Yyj, theta, eps)
}

yeojohnsontr <- function(Y, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_yeojohnsontr`, Y, theta, eps)
}

lhBCf <- function(Y, Phi, Mu, sigma2, theta) {
    .Call(`_BayesianLASSOMonitoring_lhBCf`, Y, Phi, Mu, sigma2, theta)
}

lhYJf <- function(Y, Phi, Mu, sigma2, theta) {
    .Call(`_BayesianLASSOMonitoring_lhYJf`, Y, Phi, Mu, sigma2, theta)
}

thetaBoxCoxMH <- function(Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol) {
    .Call(`_BayesianLASSOMonitoring_thetaBoxCoxMH`, Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol)
}

thetaYeoJohnsonMH <- function(Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol) {
    .Call(`_BayesianLASSOMonitoring_thetaYeoJohnsonMH`, Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol)
}

GibbsRFLSMBoxCoxcpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateBC, theta, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMBoxCoxcpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateBC, theta, nsim, by, burnin, tol, G, oldpars, H)
}

rtrnorm <- function(n, mean, sd, lower, upper) {
    .Call(`_BayesianLASSOMonitoring_rtrnorm`, n, mean, sd, lower, upper)
}

GibbsRFLSMYeoJohnsonZcpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateYJ, theta, updateZ, eps, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMYeoJohnsonZcpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateYJ, theta, updateZ, eps, nsim, by, burnin, tol, G, oldpars, H)
}

getfityj <- function(Yyj, Phi, Mu, eps) {
    .Call(`_BayesianLASSOMonitoring_getfityj`, Yyj, Phi, Mu, eps)
}

getfit <- function(Yyj, Phi, Mu, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_getfit`, Yyj, Phi, Mu, theta, eps)
}

simYyjph1 <- function(Yyj, Phi, Mu, sigma2) {
    .Call(`_BayesianLASSOMonitoring_simYyjph1`, Yyj, Phi, Mu, sigma2)
}

simYph1 <- function(Yyj, Phi, Mu, sigma2, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_simYph1`, Yyj, Phi, Mu, sigma2, theta, eps)
}

simYyjph2 <- function(h, Yyjph1, Phi, Mu, sigma2) {
    .Call(`_BayesianLASSOMonitoring_simYyjph2`, h, Yyjph1, Phi, Mu, sigma2)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
simYph2 <- function(h, Yyjph1, Phi, Mu, sigma2, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_simYph2`, h, Yyjph1, Phi, Mu, sigma2, theta, eps)
}

