# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getV <- function(V, p) {
    .Call(`_BayesianMonitoring1_getV`, V, p)
}

IsolatedShift <- function(T) {
    .Call(`_BayesianMonitoring1_IsolatedShift`, T)
}

SustainedShift <- function(T) {
    .Call(`_BayesianMonitoring1_SustainedShift`, T)
}

GradualShift <- function(T) {
    .Call(`_BayesianMonitoring1_GradualShift`, T)
}

getPosterior <- function(Y, V, X, lambda2, beta0, beta1, beta2, burnin, nsim) {
    .Call(`_BayesianMonitoring1_getPosterior`, Y, V, X, lambda2, beta0, beta1, beta2, burnin, nsim)
}

getPosteriorH0 <- function(Y, V, lambda2, beta0, beta1, burnin, nsim) {
    .Call(`_BayesianMonitoring1_getPosteriorH0`, Y, V, lambda2, beta0, beta1, burnin, nsim)
}

BenjaminiHochberg <- function(FDR, beta2, side) {
    .Call(`_BayesianMonitoring1_BenjaminiHochberg`, FDR, beta2, side)
}

