# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getV <- function(Y, q) {
    .Call(`_BayesianLASSOMonitoring_getV`, Y, q)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @param a is the lower bound in absolute value.
#' @param b is the upper bound in absolute value.
#' @param mean is a mean.
#' @param sd is a standard deviation.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
rtwosegnorm <- function(n, a, b, mean, sd) {
    .Call(`_BayesianLASSOMonitoring_rtwosegnorm`, n, a, b, mean, sd)
}

getGMat <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getGMat`, T, q)
}

getPhiMat <- function(Phi, T) {
    .Call(`_BayesianLASSOMonitoring_getPhiMat`, Phi, T)
}

#' Design Matrix (MT)
#' 
#' gets a design matrix as that in MT
#'
#' @param T is length of a process.
#' @param q is the number of lags.
#' @export
#' @examples
#' getHMatMT(100, 5)
getHMatMT <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatMT`, T, q)
}

#' Design Matrix for Sustained Shift (CM)
#' 
#' gets a design matrix for sustained shift as that in CM
#'
#' @param T is length of a process.
#' @param q is the number of lags.
#' @export
#' @examples
#' getHMatSustained(100, 5)
getHMatSustained <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatSustained`, T, q)
}

#' Design Matrix for Isolated Shift (CM)
#' 
#' gets a design matrix for isolated shift as that in CM
#'
#' @param T is length of a process.
#' @param q is the number of lags.
#' @export
#' @examples
#' getHMatIsolated(100, 5)
getHMatIsolated <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatIsolated`, T, q)
}

#' gets a design matrix for gradual shift
#'
#' @param T is length of a process.
#' @param q is the number of lags.
#' @export
#' @examples
#' getHMatGradual(100, 5)
getHMatGradual <- function(T, q) {
    .Call(`_BayesianLASSOMonitoring_getHMatGradual`, T, q)
}

#' gets a design matrix for Fourier series
#'
#' @param T is length of a process.
#' @param s is the number of period
#' @param n is the number of Fourier series
#' @export
#' @examples
#' getXSeasonalityFS(100, 15, 10)
getXSeasonalityFS <- function(T, s, n) {
    .Call(`_BayesianLASSOMonitoring_getXSeasonalityFS`, T, s, n)
}

arimaxcpp <- function(Y, q, xreg) {
    .Call(`_BayesianLASSOMonitoring_arimaxcpp`, Y, q, xreg)
}

GibbsRFLSMcpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMcpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, H)
}

GibbsRFLSMUpdatecpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMUpdatecpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, G, oldpars, H)
}

GibbsRFLSMXUpdatecpp <- function(Y, q, X, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMXUpdatecpp`, Y, q, X, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, nsim, by, burnin, tol, G, oldpars, H)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
lhf <- function(Y, Phi, Mu, sigma2) {
    .Call(`_BayesianLASSOMonitoring_lhf`, Y, Phi, Mu, sigma2)
}

boxcoxtr <- function(Y, theta) {
    .Call(`_BayesianLASSOMonitoring_boxcoxtr`, Y, theta)
}

invboxcoxtr <- function(Ybc, theta) {
    .Call(`_BayesianLASSOMonitoring_invboxcoxtr`, Ybc, theta)
}

invyeojohnsontr <- function(Yyj, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_invyeojohnsontr`, Yyj, theta, eps)
}

yeojohnsontr <- function(Y, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_yeojohnsontr`, Y, theta, eps)
}

lhBCf <- function(Y, Phi, Mu, sigma2, theta) {
    .Call(`_BayesianLASSOMonitoring_lhBCf`, Y, Phi, Mu, sigma2, theta)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
lhYJf <- function(Y, Phi, Mu, sigma2, theta) {
    .Call(`_BayesianLASSOMonitoring_lhYJf`, Y, Phi, Mu, sigma2, theta)
}

thetaBoxCoxMH <- function(Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol) {
    .Call(`_BayesianLASSOMonitoring_thetaBoxCoxMH`, Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol)
}

thetaYeoJohnsonMH <- function(Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol) {
    .Call(`_BayesianLASSOMonitoring_thetaYeoJohnsonMH`, Y, Phi, Mu, sigma2, oldtheta, burnin, nsim, tol)
}

GibbsRFLSMBoxCoxcpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateBC, theta, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMBoxCoxcpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateBC, theta, nsim, by, burnin, tol, G, oldpars, H)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
rtrnorm <- function(n, mean, sd, lower, upper) {
    .Call(`_BayesianLASSOMonitoring_rtrnorm`, n, mean, sd, lower, upper)
}

GibbsRFLSMYeoJohnsonZcpp <- function(Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateYJ, theta, updateZ, eps, nsim, by, burnin, tol, G = NULL, oldpars = NULL, H = NULL) {
    .Call(`_BayesianLASSOMonitoring_GibbsRFLSMYeoJohnsonZcpp`, Y, q, A, a, b, alpha, beta, theta1, theta2, xi2, method, bound0, boundqplus1, updateYJ, theta, updateZ, eps, nsim, by, burnin, tol, G, oldpars, H)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
getfityj <- function(Yyj, Phi, Mu, eps) {
    .Call(`_BayesianLASSOMonitoring_getfityj`, Yyj, Phi, Mu, eps)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
getfit <- function(Yyj, Phi, Mu, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_getfit`, Yyj, Phi, Mu, theta, eps)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
simYyjph1 <- function(Yyj, Phi, Mu, sigma2) {
    .Call(`_BayesianLASSOMonitoring_simYyjph1`, Yyj, Phi, Mu, sigma2)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
simYph1 <- function(Yyj, Phi, Mu, sigma2, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_simYph1`, Yyj, Phi, Mu, sigma2, theta, eps)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
simYyjph2 <- function(h, Yyjph1, Phi, Mu, sigma2) {
    .Call(`_BayesianLASSOMonitoring_simYyjph2`, h, Yyjph1, Phi, Mu, sigma2)
}

#' Absolute-value-constrained normal distribution
#' 
#' gets a sample from a normal distribution whose absolute observations are constrained.
#'
#' @param n is sample size.
#' @export
#' @examples
#' rtwosegnorm(10, 1, 2, 0, 1)
simYph2 <- function(h, Yyjph1, Phi, Mu, sigma2, theta, eps) {
    .Call(`_BayesianLASSOMonitoring_simYph2`, h, Yyjph1, Phi, Mu, sigma2, theta, eps)
}

